# fly.toml app configuration file generated for mirrorcaps-server on 2025-07-01T18:45:32+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mirrorcaps-server'
primary_region = 'lax'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256MiB'
  cpu_kind = 'shared'
  cpus = 1
